// data.js — copy in English and Indonesian. Japanese "source" lines live in index.html (data-jp).

export const translations = {
    en: {
        'meta-title': 'VANT Project — a creative collective',
        'status-works': '3 projects',
        'status-soon': 'Coming soon',
        'status-open': 'Open for projects',
        'area-academy-d': 'Courses with practitioners',
        'area-creative-d': 'Design, stories, games, experiments',
        'area-creative': 'Creative projects',
        'area-apps-d': 'Survey, management and other practical tools',
        'area-apps': 'Apps for everyday work',
        'area-photo-d': 'Photos by VANT and the people who’ve joined us',
        'area-photo': 'Photography',
        'area-tools-d': 'AnTiMa, TeaFlow and GAIA',
        'area-tools': 'Learning & AI tools',
        'skip': 'Skip to content',
        'intro-skip': 'Skip intro',
        'intro-learn': 'Made at VANT',
        'intro-through': 'anything creative:',
        'intro-w1': 'apps',
        'intro-w2': 'photos',
        'intro-w3': 'courses',
        'intro-antima': 'AI and everyday apps',
        'intro-teaflow': 'people, places, events',
        'intro-gaia': 'courses, coming soon',
        'intro-tag': 'Simple. Fun. Made together.',
        'intro-p1': 'Tools',
        'intro-p2': 'Photography',
        'intro-p3': 'Academy',
        'nav-about': 'Mission',
        'nav-members': 'Vibra × AnTiMa',
        'nav-works': 'Works',
        'nav-credits': 'Credits',
        'nav-contact': 'Contact',
        'jump-label': 'Chapters',
        'nav-photo': 'Photography',
        'cut-photo': 'Photos by VANT and the people who’ve joined us',
        'status-gallery': 'Gallery',
        'cc-label': 'Subtitles',

        'hero-title': 'A home for creative work of every kind.',
        'hero-lead': 'VANT started with AI tools that teach languages through anime, comics and games. Today we take on any creative project: photography, practical apps, creative experiments, and soon, courses.',
        'hero-body': 'AnTiMa builds the tools. Vibra, our legacy project, gives them their rule: keep everything simple.',
        'hero-cta': 'See the works',
        'hero-discord': 'Join AnTiMa on Discord',
        'index-title': 'What we do',
        'cut-antima': 'AI companion for Discord communities',
        'cut-teaflow': 'AI tutor you practise speaking with',
        'cut-gaia': 'AI game master for text RPGs',
        'index-open': 'Open to collaborators',

        'about-1': 'Good work starts with something you love.',
        'about-2': 'VANT began with anime, comics, games and language learning, and grew into a home for any creative project.',
        'about-3': 'Photos, apps, creative experiments and courses: if it’s made with care, it belongs here.',
        'values-title': 'What every project has to pass',
        'v-fun': 'Fun',
        'v-fun-d': 'If it isn’t enjoyable, it isn’t finished.',
        'v-access': 'Accessible',
        'v-access-d': 'Easy to start and hassle-free, for anyone.',
        'v-tech': 'Technology',
        'v-tech-d': 'Modern tools do the heavy lifting so the work feels natural.',
        'v-comm': 'Community',
        'v-comm-d': 'Made with the people who join us, and shared with the communities we belong to.',

        'members-title': 'Two projects, one team.',
        'vibra-motto': 'Simplify.',
        'vibra-body': 'Vibra began in 2023 as Vibra Store, a game-jockey service that took the grind out of games. The store is now a legacy project; VANT carries forward its meaning and its goal: remove the friction, so learners only meet the fun part.',
        'antima-motto': 'Anime Translation Manga.',
        'antima-body': 'The creative and technical core of VANT, where anime, language learning and AI meet. AnTiMa builds the anime-inspired tools and AI features, and keeps growing.',

        'works-title': 'The works',
        'works-lead': 'Some of what we’ve built so far: three projects, live or open source. Open any screenshot to see more.',
        'view-all': 'View screenshots',
        'status-live': 'Live',
        'status-wip': 'In progress',
        'status-oss': 'Open source',
        'antima-desc': 'An AI companion for Discord servers that helps communities learn languages together. It translates, shares cultural trivia and writes personalised practice prompts in an anime-and-manga voice, remembers past chats, adapts its personality, recognises images and reacts with GIFs.',
        'teaflow-desc': 'An AI conversation tutor you practise with out loud. Google Gemini runs the dialogue and ElevenLabs gives it a natural voice, with full speech-to-text and text-to-speech.',
        'gaia-desc': 'A text role-playing game engine with Google Gemini as game master. It generates the world, characters and branching storylines in real time from your choices.',
        'built-with': 'Built with',
        'link-discord': 'Join the Discord',
        'link-repo': 'Source on GitHub',
        'next-title': 'Your project here',
        'next-body': 'The next one is open. Bring an idea, a community, a skill or a project, and let’s make it together.',
        'next-link': 'Start a conversation',

        'credits-title': 'Credits',
        'cr-lead': 'Lead developer, AI & prompt engineering',
        'cr-bio': 'I build AI-powered applications and design the prompts that make them behave. I got hooked on how machines learn and adapt, and now I point that curiosity at tools for the communities I’m part of. Anime and games are where I unwind, and where most of VANT’s ideas come from.',
        'cr-simplify': 'Legacy & guiding idea · Vibra Store, 2023',
        'cr-core': 'Creative & technical core',
        'cr-stack': 'Built with',

        'contact-title': 'Want to build something together?',
        'contact-body': 'Creators, developers, photographers, practitioners and partners: write to us about a project or a collaboration.',
        'contact-cta': 'Email VANT',
        'dial-top': 'Back to top',
        'secret-found': 'Secret found',
        'dev-note': 'Note from the developer: thanks for poking around. Say hi on Discord!',

        'footer-text': '© 2026 VANT Project. All rights reserved.',
        'footer-end': 'End of transcript',
        'viewer-close': 'Close',
        'viewer-prev': 'Previous screenshot',
        'viewer-next': 'Next screenshot',
        'timeline': 'Page timeline'
    },
    id: {
        'meta-title': 'Proyek VANT — kolektif kreatif',
        'status-works': '3 proyek',
        'status-soon': 'Segera hadir',
        'status-open': 'Terbuka untuk proyek',
        'area-academy-d': 'Kursus bersama praktisi',
        'area-creative-d': 'Desain, cerita, game, eksperimen',
        'area-creative': 'Proyek kreatif',
        'area-apps-d': 'Survei, manajemen, dan alat praktis lainnya',
        'area-apps': 'Aplikasi untuk kerja sehari-hari',
        'area-photo-d': 'Foto dari VANT dan orang-orang yang bergabung',
        'area-photo': 'Fotografi',
        'area-tools-d': 'AnTiMa, TeaFlow, dan GAIA',
        'area-tools': 'Alat belajar & AI',
        'skip': 'Langsung ke konten',
        'intro-skip': 'Lewati intro',
        'intro-learn': 'Dibuat di VANT',
        'intro-through': 'apa pun yang kreatif:',
        'intro-w1': 'aplikasi',
        'intro-w2': 'foto',
        'intro-w3': 'kursus',
        'intro-antima': 'aplikasi AI & sehari-hari',
        'intro-teaflow': 'orang, tempat, acara',
        'intro-gaia': 'kursus, segera hadir',
        'intro-tag': 'Sederhana. Seru. Dibuat bersama.',
        'intro-p1': 'Alat',
        'intro-p2': 'Fotografi',
        'intro-p3': 'Akademi',
        'nav-about': 'Misi',
        'nav-members': 'Vibra × AnTiMa',
        'nav-works': 'Karya',
        'nav-credits': 'Kredit',
        'nav-contact': 'Kontak',
        'jump-label': 'Bab',
        'nav-photo': 'Fotografi',
        'cut-photo': 'Foto dari VANT dan orang-orang yang bergabung',
        'status-gallery': 'Galeri',
        'cc-label': 'Subtitle',

        'hero-title': 'Rumah bagi karya kreatif apa pun.',
        'hero-lead': 'VANT berawal dari alat AI untuk belajar bahasa lewat anime, komik, dan game. Kini kami mengerjakan proyek kreatif apa pun: fotografi, aplikasi praktis, eksperimen kreatif, dan segera, kursus.',
        'hero-body': 'AnTiMa membangun alatnya. Vibra, proyek warisan kami, memberi aturannya: buat semuanya tetap sederhana.',
        'hero-cta': 'Lihat karya kami',
        'hero-discord': 'Gabung AnTiMa di Discord',
        'index-title': 'Yang kami kerjakan',
        'cut-antima': 'Teman AI untuk komunitas Discord',
        'cut-teaflow': 'Tutor AI untuk latihan berbicara',
        'cut-gaia': 'Game master AI untuk RPG teks',
        'index-open': 'Terbuka untuk kolaborator',

        'about-1': 'Karya yang baik berawal dari hal yang kamu sukai.',
        'about-2': 'VANT berawal dari anime, komik, game, dan belajar bahasa, lalu tumbuh menjadi rumah bagi proyek kreatif apa pun.',
        'about-3': 'Foto, aplikasi, eksperimen kreatif, dan kursus: kalau dibuat dengan sepenuh hati, tempatnya di sini.',
        'values-title': 'Yang harus dipenuhi setiap proyek',
        'v-fun': 'Menyenangkan',
        'v-fun-d': 'Kalau belum menyenangkan, berarti belum selesai.',
        'v-access': 'Mudah diakses',
        'v-access-d': 'Mudah dimulai dan tanpa repot, untuk siapa saja.',
        'v-tech': 'Teknologi',
        'v-tech-d': 'Alat modern mengerjakan bagian beratnya agar karya terasa alami.',
        'v-comm': 'Komunitas',
        'v-comm-d': 'Dibuat bersama orang-orang yang bergabung, dan dibagikan ke komunitas tempat kami berada.',

        'members-title': 'Dua proyek, satu tim.',
        'vibra-motto': 'Sederhanakan.',
        'vibra-body': 'Vibra dimulai pada 2023 sebagai Vibra Store, layanan joki game yang menghilangkan bagian membosankan dari game. Toko itu kini proyek warisan; VANT meneruskan makna dan tujuannya: hilangkan hambatan, agar pelajar hanya bertemu bagian serunya.',
        'antima-motto': 'Anime Translation Manga.',
        'antima-body': 'Inti kreatif dan teknis VANT, tempat anime, belajar bahasa, dan AI bertemu. AnTiMa membangun alat bernuansa anime dan fitur AI-nya, dan terus berkembang.',

        'works-title': 'Karya kami',
        'works-lead': 'Sebagian yang sudah kami buat: tiga proyek, aktif atau sumber terbuka. Buka tangkapan layar mana pun untuk melihat lebih banyak.',
        'view-all': 'Lihat tangkapan layar',
        'status-live': 'Aktif',
        'status-wip': 'Dalam pengembangan',
        'status-oss': 'Sumber terbuka',
        'antima-desc': 'Teman AI untuk server Discord yang membantu komunitas belajar bahasa bersama. Ia menerjemahkan, berbagi trivia budaya, dan menulis latihan yang dipersonalisasi dengan gaya anime dan manga, mengingat obrolan, menyesuaikan kepribadian, mengenali gambar, dan membalas dengan GIF.',
        'teaflow-desc': 'Tutor percakapan AI untuk latihan berbicara langsung. Google Gemini menjalankan dialognya dan ElevenLabs memberinya suara alami, lengkap dengan speech-to-text dan text-to-speech.',
        'gaia-desc': 'Mesin game role-playing berbasis teks dengan Google Gemini sebagai game master. Ia membangun dunia, karakter, dan alur cerita bercabang secara real-time dari pilihanmu.',
        'built-with': 'Dibuat dengan',
        'link-discord': 'Gabung Discord',
        'link-repo': 'Kode di GitHub',
        'next-title': 'Proyekmu di sini',
        'next-body': 'Slot berikutnya masih terbuka. Bawa ide, komunitas, keahlian, atau proyek, dan ayo buat bersama.',
        'next-link': 'Mulai percakapan',

        'credits-title': 'Kredit',
        'cr-lead': 'Pengembang utama, AI & prompt engineering',
        'cr-bio': 'Saya membuat aplikasi bertenaga AI dan merancang prompt yang membuatnya bekerja dengan baik. Saya terpikat pada cara mesin belajar dan beradaptasi, dan kini rasa penasaran itu saya arahkan ke alat untuk komunitas tempat saya berada. Anime dan game adalah tempat saya bersantai, dan sumber sebagian besar ide VANT.',
        'cr-simplify': 'Warisan & gagasan utama · Vibra Store, 2023',
        'cr-core': 'Inti kreatif & teknis',
        'cr-stack': 'Dibuat dengan',

        'contact-title': 'Mau membangun sesuatu bersama?',
        'contact-body': 'Kreator, pengembang, fotografer, praktisi, dan mitra: kirimi kami pesan tentang proyek atau kolaborasi.',
        'contact-cta': 'Email VANT',
        'dial-top': 'Kembali ke atas',
        'secret-found': 'Rahasia ditemukan',
        'dev-note': 'Catatan dari pengembang: terima kasih sudah iseng menjelajah. Sapa kami di Discord!',
        'footer-text': '© 2026 Proyek VANT. Hak cipta dilindungi.',
        'footer-end': 'Akhir transkrip',
        'viewer-close': 'Tutup',
        'viewer-prev': 'Tangkapan sebelumnya',
        'viewer-next': 'Tangkapan berikutnya',
        'timeline': 'Linimasa halaman'
    }
};

export const projects = {
    antima: { name: 'AnTiMa', images: ['img/antimabot_1.png', 'img/WEB.png', 'img/antimabot_2.png', 'img/antimabot_3.png'] },
    teaflow: { name: 'TeaFlow', images: ['img/TeaF_1.png', 'img/TeaF_3.png', 'img/TeaF_4.png'] },
    gaia: { name: 'GAIA', images: ['img/gaia_thmb.png', 'img/gaia_1.png', 'img/gaia_4.png', 'img/gaia_2.png', 'img/gaia_3.png'] }
};

// Short quips for secrets and hints: Japanese first, then the reader's language.
export const quips = {
    idle:      { jp: 'ねぇねぇ…', en: 'Psst… gamers know a certain code. ↑↑↓↓', id: 'Psst… gamer pasti tahu kode tertentu. ↑↑↓↓' },
    idleTouch: { jp: 'ねぇねぇ…', en: 'Psst… swipe ↑↑↓↓←→←→ anywhere, then tap twice.', id: 'Psst… geser ↑↑↓↓←→←→ di mana saja, lalu ketuk dua kali.' },
    konami:    { jp: '通だね！', en: 'The Konami code? A true gamer!', id: 'Kode Konami? Gamer sejati!' },
    called:    { jp: '呼んだ？', en: 'AnTiMa heard you call her name.', id: 'AnTiMa mendengar namanya dipanggil.' },
    vibra:     { jp: 'シンプルに！', en: 'Vibra says: keep it simple.', id: 'Kata Vibra: buat tetap sederhana.' },
    dizzy:     { jp: '目が回る〜', en: 'Round and round… the dial is dizzy.', id: 'Berputar terus… dialnya pusing.' },
    allFound:  { jp: 'コンプリート！', en: 'All secrets found. You’re officially one of us.', id: 'Semua rahasia ditemukan. Kamu resmi bagian dari kami.' }
};
