// data.js — copy in English and Indonesian. Japanese "source" lines live in index.html (data-jp).

export const translations = {
    en: {
        'meta-title': 'VANT Project — Vibra × AnTiMa',
        'skip': 'Skip to content',
        'intro-skip': 'Skip intro',
        'intro-learn': 'Learn languages',
        'intro-through': 'through',
        'intro-w1': 'anime',
        'intro-w2': 'comics',
        'intro-w3': 'games',
        'intro-antima': 'a Discord companion',
        'intro-teaflow': 'a speaking tutor',
        'intro-gaia': 'an AI game master',
        'intro-tag': 'Simple. Fun. Powered by AI.',
        'nav-about': 'Mission',
        'nav-members': 'Vibra × AnTiMa',
        'nav-works': 'Works',
        'nav-credits': 'Credits',
        'nav-contact': 'Contact',
        'jump-label': 'Chapters',
        'cc-label': 'Subtitles',

        'hero-title': 'Learn languages through the anime, comics and games you already love.',
        'hero-lead': 'VANT builds AI tools for fans who would rather learn from a manga panel than a textbook: a Discord companion, a speaking tutor and a story-driven RPG.',
        'hero-body': 'AnTiMa builds the tools. Vibra, our legacy project, gives them their rule: keep everything simple.',
        'hero-cta': 'See the works',
        'hero-discord': 'Join AnTiMa on Discord',
        'index-title': 'What we’ve made',
        'cut-antima': 'AI companion for Discord communities',
        'cut-teaflow': 'AI tutor you practise speaking with',
        'cut-gaia': 'AI game master for text RPGs',
        'index-open': 'Open to collaborators',

        'about-1': 'Learning a language shouldn’t feel like homework.',
        'about-2': 'VANT is for people who would rather learn Japanese from a manga panel than a textbook drill.',
        'about-3': 'So we build tools inside the anime, comics and games world fans already love, where practice feels like play.',
        'values-title': 'What every release has to pass',
        'v-fun': 'Fun',
        'v-fun-d': 'If it isn’t enjoyable, it isn’t finished.',
        'v-access': 'Accessible',
        'v-access-d': 'Easy to start and hassle-free, for any learner.',
        'v-tech': 'Technology',
        'v-tech-d': 'Modern AI does the heavy lifting so learning feels natural.',
        'v-comm': 'Community',
        'v-comm-d': 'Built for fan spaces like Discord, where people already learn together.',

        'members-title': 'Two projects, one team.',
        'vibra-motto': 'Simplify.',
        'vibra-body': 'Vibra began in 2023 as Vibra Store, a game-jockey service that took the grind out of games. The store is now a legacy project; VANT carries forward its meaning and its goal: remove the friction, so learners only meet the fun part.',
        'antima-motto': 'Anime Translation Manga.',
        'antima-body': 'The creative and technical core of VANT, where anime, language learning and AI meet. AnTiMa builds the anime-inspired tools and AI features, and keeps growing.',

        'works-title': 'The works',
        'works-lead': 'Three projects, live or open source. Open any screenshot to see more.',
        'view-all': 'View screenshots',
        'status-live': 'Live',
        'status-wip': 'In progress',
        'status-oss': 'Open source',
        'antima-desc': 'An AI companion for Discord servers that helps communities learn languages together. It translates, shares cultural trivia and writes personalised practice prompts in an anime-and-manga voice, remembers past chats, adapts its personality, recognises images and reacts with GIFs.',
        'teaflow-desc': 'An AI conversation tutor you practise with out loud. Google Gemini runs the dialogue and ElevenLabs gives it a natural voice, with full speech-to-text and text-to-speech.',
        'gaia-desc': 'A text role-playing game engine with Google Gemini as game master. It generates the world, characters and branching storylines in real time from your choices.',
        'built-with': 'Built with',
        'link-discord': 'Join the Discord',
        'link-repo': 'Source on GitHub',
        'next-title': 'Your project here',
        'next-body': 'The next one is open. If you have an idea, a community or a skill that fits, let’s make it together.',
        'next-link': 'Start a conversation',

        'credits-title': 'Credits',
        'cr-lead': 'Lead developer, AI & prompt engineering',
        'cr-bio': 'I build AI-powered applications and design the prompts that make them behave. I got hooked on how machines learn and adapt, and now I point that curiosity at tools for the communities I’m part of. Anime and games are where I unwind, and where most of VANT’s ideas come from.',
        'cr-simplify': 'Legacy & guiding idea · Vibra Store, 2023',
        'cr-core': 'Creative & technical core',
        'cr-stack': 'Built with',

        'contact-title': 'Want to build something together?',
        'contact-body': 'Communities, developers, translators, partners: write to us about a collaboration.',
        'contact-cta': 'Email VANT',
        'dial-top': 'Back to top',
        'secret-found': 'Secret found',
        'dev-note': 'Note from the developer: thanks for poking around. Say hi on Discord!',

        'footer-text': '© 2026 VANT Project. All rights reserved.',
        'footer-end': 'End of transcript',
        'viewer-close': 'Close',
        'viewer-prev': 'Previous screenshot',
        'viewer-next': 'Next screenshot',
        'timeline': 'Page timeline'
    },
    id: {
        'meta-title': 'Proyek VANT — Vibra × AnTiMa',
        'skip': 'Langsung ke konten',
        'intro-skip': 'Lewati intro',
        'intro-learn': 'Belajar bahasa',
        'intro-through': 'lewat',
        'intro-w1': 'anime',
        'intro-w2': 'komik',
        'intro-w3': 'game',
        'intro-antima': 'teman di Discord',
        'intro-teaflow': 'tutor bicara',
        'intro-gaia': 'game master AI',
        'intro-tag': 'Sederhana. Seru. Didukung AI.',
        'nav-about': 'Misi',
        'nav-members': 'Vibra × AnTiMa',
        'nav-works': 'Karya',
        'nav-credits': 'Kredit',
        'nav-contact': 'Kontak',
        'jump-label': 'Bab',
        'cc-label': 'Subtitle',

        'hero-title': 'Belajar bahasa lewat anime, komik, dan game yang sudah kamu sukai.',
        'hero-lead': 'VANT membuat alat AI untuk penggemar yang lebih suka belajar dari panel manga daripada buku teks: teman Discord, tutor bicara, dan RPG berbasis cerita.',
        'hero-body': 'AnTiMa membangun alatnya. Vibra, proyek warisan kami, memberi aturannya: buat semuanya tetap sederhana.',
        'hero-cta': 'Lihat karya kami',
        'hero-discord': 'Gabung AnTiMa di Discord',
        'index-title': 'Yang sudah kami buat',
        'cut-antima': 'Teman AI untuk komunitas Discord',
        'cut-teaflow': 'Tutor AI untuk latihan berbicara',
        'cut-gaia': 'Game master AI untuk RPG teks',
        'index-open': 'Terbuka untuk kolaborator',

        'about-1': 'Belajar bahasa tidak seharusnya terasa seperti PR.',
        'about-2': 'VANT untuk kamu yang lebih suka belajar bahasa Jepang dari panel manga daripada latihan buku teks.',
        'about-3': 'Jadi kami membuat alat di dalam dunia anime, komik, dan game yang sudah kamu sukai, tempat latihan terasa seperti bermain.',
        'values-title': 'Yang harus dipenuhi setiap rilis',
        'v-fun': 'Menyenangkan',
        'v-fun-d': 'Kalau belum menyenangkan, berarti belum selesai.',
        'v-access': 'Mudah diakses',
        'v-access-d': 'Mudah dimulai dan tanpa repot, untuk siapa saja.',
        'v-tech': 'Teknologi',
        'v-tech-d': 'AI modern mengerjakan bagian beratnya agar belajar terasa alami.',
        'v-comm': 'Komunitas',
        'v-comm-d': 'Dibuat untuk ruang penggemar seperti Discord, tempat orang sudah belajar bersama.',

        'members-title': 'Dua proyek, satu tim.',
        'vibra-motto': 'Sederhanakan.',
        'vibra-body': 'Vibra dimulai pada 2023 sebagai Vibra Store, layanan joki game yang menghilangkan bagian membosankan dari game. Toko itu kini proyek warisan; VANT meneruskan makna dan tujuannya: hilangkan hambatan, agar pelajar hanya bertemu bagian serunya.',
        'antima-motto': 'Anime Translation Manga.',
        'antima-body': 'Inti kreatif dan teknis VANT, tempat anime, belajar bahasa, dan AI bertemu. AnTiMa membangun alat bernuansa anime dan fitur AI-nya, dan terus berkembang.',

        'works-title': 'Karya kami',
        'works-lead': 'Tiga proyek, aktif atau sumber terbuka. Buka tangkapan layar mana pun untuk melihat lebih banyak.',
        'view-all': 'Lihat tangkapan layar',
        'status-live': 'Aktif',
        'status-wip': 'Dalam pengembangan',
        'status-oss': 'Sumber terbuka',
        'antima-desc': 'Teman AI untuk server Discord yang membantu komunitas belajar bahasa bersama. Ia menerjemahkan, berbagi trivia budaya, dan menulis latihan yang dipersonalisasi dengan gaya anime dan manga, mengingat obrolan, menyesuaikan kepribadian, mengenali gambar, dan membalas dengan GIF.',
        'teaflow-desc': 'Tutor percakapan AI untuk latihan berbicara langsung. Google Gemini menjalankan dialognya dan ElevenLabs memberinya suara alami, lengkap dengan speech-to-text dan text-to-speech.',
        'gaia-desc': 'Mesin game role-playing berbasis teks dengan Google Gemini sebagai game master. Ia membangun dunia, karakter, dan alur cerita bercabang secara real-time dari pilihanmu.',
        'built-with': 'Dibuat dengan',
        'link-discord': 'Gabung Discord',
        'link-repo': 'Kode di GitHub',
        'next-title': 'Proyekmu di sini',
        'next-body': 'Slot berikutnya masih terbuka. Kalau kamu punya ide, komunitas, atau keahlian yang cocok, ayo buat bersama.',
        'next-link': 'Mulai percakapan',

        'credits-title': 'Kredit',
        'cr-lead': 'Pengembang utama, AI & prompt engineering',
        'cr-bio': 'Saya membuat aplikasi bertenaga AI dan merancang prompt yang membuatnya bekerja dengan baik. Saya terpikat pada cara mesin belajar dan beradaptasi, dan kini rasa penasaran itu saya arahkan ke alat untuk komunitas tempat saya berada. Anime dan game adalah tempat saya bersantai, dan sumber sebagian besar ide VANT.',
        'cr-simplify': 'Warisan & gagasan utama · Vibra Store, 2023',
        'cr-core': 'Inti kreatif & teknis',
        'cr-stack': 'Dibuat dengan',

        'contact-title': 'Mau membangun sesuatu bersama?',
        'contact-body': 'Komunitas, pengembang, penerjemah, mitra: kirimi kami pesan tentang kolaborasi.',
        'contact-cta': 'Email VANT',
        'dial-top': 'Kembali ke atas',
        'secret-found': 'Rahasia ditemukan',
        'dev-note': 'Catatan dari pengembang: terima kasih sudah iseng menjelajah. Sapa kami di Discord!',
        'footer-text': '© 2026 Proyek VANT. Hak cipta dilindungi.',
        'footer-end': 'Akhir transkrip',
        'viewer-close': 'Tutup',
        'viewer-prev': 'Tangkapan sebelumnya',
        'viewer-next': 'Tangkapan berikutnya',
        'timeline': 'Linimasa halaman'
    }
};

export const projects = {
    antima: { name: 'AnTiMa', images: ['img/antimabot_1.png', 'img/WEB.png', 'img/antimabot_2.png', 'img/antimabot_3.png'] },
    teaflow: { name: 'TeaFlow', images: ['img/TeaF_1.png', 'img/TeaF_3.png', 'img/TeaF_4.png'] },
    gaia: { name: 'GAIA', images: ['img/gaia_thmb.png', 'img/gaia_1.png', 'img/gaia_4.png', 'img/gaia_2.png', 'img/gaia_3.png'] }
};

// Short quips for secrets and hints: Japanese first, then the reader's language.
export const quips = {
    idle:      { jp: 'ねぇねぇ…', en: 'Psst… gamers know a certain code. ↑↑↓↓', id: 'Psst… gamer pasti tahu kode tertentu. ↑↑↓↓' },
    idleTouch: { jp: 'ねぇねぇ…', en: 'Psst… swipe ↑↑↓↓←→←→ anywhere, then tap twice.', id: 'Psst… geser ↑↑↓↓←→←→ di mana saja, lalu ketuk dua kali.' },
    konami:    { jp: '通だね！', en: 'The Konami code? A true gamer!', id: 'Kode Konami? Gamer sejati!' },
    called:    { jp: '呼んだ？', en: 'AnTiMa heard you call her name.', id: 'AnTiMa mendengar namanya dipanggil.' },
    vibra:     { jp: 'シンプルに！', en: 'Vibra says: keep it simple.', id: 'Kata Vibra: buat tetap sederhana.' },
    dizzy:     { jp: '目が回る〜', en: 'Round and round… the dial is dizzy.', id: 'Berputar terus… dialnya pusing.' },
    allFound:  { jp: 'コンプリート！', en: 'All secrets found. You’re officially one of us.', id: 'Semua rahasia ditemukan. Kamu resmi bagian dari kami.' }
};
